# # spring.application.name=project
# spring.datasource.url=jdbc:mysql://localhost:3306/lostfound
# spring.datasource.username=root
# spring.datasource.password=root

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d6ofdmbh46gs73ajisf0-a/tt_database_3y7r

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}