spring.datasource.url=jdbc:postgresql://dpg-d6ofdmbh46gs73ajisf0-a.oregon-postgres.render.com:5432/tt_database_3y7r

spring.datasource.username=tt_database_3y7r_user
spring.datasource.password=928gMKp2r2nFJvSBdH86dlz1lvaIIYvi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true